-- 1. Справочник рейтингов MPA
CREATE TABLE IF NOT EXISTS ratingMPA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

-- 2. Справочник жанров
CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

-- 3. Справочник статусов дружбы
CREATE TABLE IF NOT EXISTS friends_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

-- 4. Пользователи
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    login VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    birthday DATE NOT NULL
);

-- 5. Фильмы
CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    rating_id INTEGER NOT NULL,
    CONSTRAINT fk_films_genre FOREIGN KEY (genre_id) REFERENCES genre (id),
    CONSTRAINT fk_films_rating FOREIGN KEY (rating_id) REFERENCES ratingMPA (id)
);

-- 6. Лайки (составной первичный ключ)
CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_likes_film FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 7. Друзья (составной первичный ключ)
CREATE TABLE IF NOT EXISTS friends (
    user1_id INTEGER NOT NULL,
    user2_id INTEGER NOT NULL,
    status INTEGER NOT NULL,
    CONSTRAINT pk_friends PRIMARY KEY (user1_id, user2_id),
    CONSTRAINT fk_friends_user1 FOREIGN KEY (user1_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friends_user2 FOREIGN KEY (user2_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friends_status FOREIGN KEY (status) REFERENCES friends_status (id)
);