DELETE FROM LIKES;
DELETE FROM FILM_GENRE;
DELETE FROM FRIENDS;
DELETE FROM FILMS;
DELETE FROM USERS;
DELETE FROM GENRE;
DELETE FROM RATINGMPA;
DELETE FROM FRIENDS_STATUS;

ALTER TABLE FILMS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE RATINGMPA ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FRIENDS_STATUS ALTER COLUMN id RESTART WITH 1;